# Generated by Django 4.2.2 on 2023-09-22 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_followings_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='followers',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followings',
            name='followings',
            field=models.ManyToManyField(related_name='follwer', to=settings.AUTH_USER_MODEL),
        ),
    ]
