# Generated by Django 4.2.2 on 2023-09-22 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_followers_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followings',
            name='followings',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
