# Generated by Django 4.2.2 on 2023-09-22 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_followers_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
